
package vista;

import BaseDatos.ConexionBD;
import controlador.Controlador_FRM_Login;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import modelo.ArchivosUsuario;
import modelo.Metodos_XML_Usuarios;

public class FRM_Login extends javax.swing.JFrame {

    public Controlador_FRM_Login controlador_frm_login;
    ArchivosUsuario archivo;
    Metodos_XML_Usuarios metodosXML;
    ConexionBD conexionBD;
    ButtonGroup botones;
    FRM_VentanaPrincipal frm_ventanaPrincipal;
    FRM_MantenimientoUsuarios frm_mantenimientoUsuarios;

    public FRM_Login() {
        initComponents();
        
        archivo = new ArchivosUsuario();
        
        frm_ventanaPrincipal = new FRM_VentanaPrincipal();
        frm_mantenimientoUsuarios = new FRM_MantenimientoUsuarios(this);
        controlador_frm_login = new Controlador_FRM_Login(this, archivo,frm_ventanaPrincipal,frm_mantenimientoUsuarios,metodosXML);
        agregarEventos(controlador_frm_login);
       
        botones = new ButtonGroup();
        botones.add(jrbArchivosPlanos);
        botones.add(jrbBD);
        botones.add(jrbXML);
        agregarEventosButtons(controlador_frm_login);
        desactivarLogin();
    }
    public void activarLogin()
    {
        jtNombreUsuario.setEnabled(true);
        jpfContrasena.setEnabled(true);
        btnAceptar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnRegistro.setEnabled(true);
    }
    public void desactivarLogin()
    {
        jtNombreUsuario.setEnabled(false);
        jpfContrasena.setEnabled(false);
        btnAceptar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnRegistro.setEnabled(false);
    }
    public String botones() {
        String dato = "";
        if (jrbArchivosPlanos.isSelected() == true) {
            dato = "ArchivosPlanos";
        }
        if (jrbBD.isSelected() == true) {
            dato = "BaseDeDatos";
        }
        if (jrbXML.isSelected() == true) {
            dato = "XML";
        }

        return dato;
    }

    public String[] devolverInformacionLogin() {
        String arreglo[] = new String[2];
        arreglo[0] = this.jtNombreUsuario.getText();
        arreglo[1] = this.jpfContrasena.getText();

        return arreglo;
    }

    public void agregarEventos(Controlador_FRM_Login controlador_frm_login) {
        this.btnAceptar.addActionListener(controlador_frm_login);
        this.btnCancelar.addActionListener(controlador_frm_login);
        this.btnRegistro.addActionListener(controlador_frm_login);
    }
    
    public void agregarEventosButtons(Controlador_FRM_Login controlador_frm_login)
    {
        this.jrbArchivosPlanos.addActionListener(controlador_frm_login);
        this.jrbBD.addActionListener(controlador_frm_login);
        this.jrbXML.addActionListener(controlador_frm_login);
    }

    public String[] devolverInformacionDeInicioDeSesion() {
        String arreglo[] = new String[2];
        arreglo[0] = this.jtNombreUsuario.getText();
        arreglo[1] = this.jpfContrasena.getText();
        return arreglo;
    }

    public void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    public String getJpfContrasena() {
        return jpfContrasena.getText().trim();
    }

    public String getJtNombreUsuario() {
        return jtNombreUsuario.getText().trim();
    }
    
    public void limpiar(){
        this.jtNombreUsuario.setText("");
        this.jpfContrasena.setText("");
    }
    public String devolverNombreUsuario() 
    {
        return this.jtNombreUsuario.getText();
    }
    public String devolverContraseña() 
    {
        return this.jpfContrasena.getText();
    }
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null, mensaje);
    }
    public void limpiarCampoContraseña() 
    {
        this.jpfContrasena.setText("");
    }
    public void resetearGUI() 
    {
        this.jtNombreUsuario.setText("");
        this.jpfContrasena.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlNombreUsuario = new javax.swing.JLabel();
        jlContrasena = new javax.swing.JLabel();
        jtNombreUsuario = new javax.swing.JTextField();
        jpfContrasena = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        jrbArchivosPlanos = new javax.swing.JRadioButton();
        jrbBD = new javax.swing.JRadioButton();
        jrbXML = new javax.swing.JRadioButton();
        jlMensaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlNombreUsuario.setText("Nombre Usuario: ");

        jlContrasena.setText("Contraseña:");

        jtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreUsuarioActionPerformed(evt);
            }
        });

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check.png"))); // NOI18N
        btnAceptar.setText("Aceptar");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users.png"))); // NOI18N
        btnRegistro.setText("Registro");

        jrbArchivosPlanos.setText("Archivos Planos");
        jrbArchivosPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbArchivosPlanosActionPerformed(evt);
            }
        });

        jrbBD.setText("Base de Datos");

        jrbXML.setText("XML");

        jlMensaje.setText("¿En que fuente de información desea ingresar?");

        jLabel1.setText("_________________________________________________________");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shield.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jrbArchivosPlanos)
                        .addGap(18, 18, 18)
                        .addComponent(jrbBD)
                        .addGap(31, 31, 31)
                        .addComponent(jrbXML))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jlMensaje)))
                .addGap(51, 58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNombreUsuario)
                                    .addComponent(jlContrasena))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jpfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addGap(21, 21, 21))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMensaje)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbArchivosPlanos)
                    .addComponent(jrbBD)
                    .addComponent(jrbXML))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNombreUsuario)
                            .addComponent(jtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlContrasena)
                            .addComponent(jpfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAceptar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreUsuarioActionPerformed

    private void jrbArchivosPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbArchivosPlanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbArchivosPlanosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlContrasena;
    private javax.swing.JLabel jlMensaje;
    private javax.swing.JLabel jlNombreUsuario;
    private javax.swing.JPasswordField jpfContrasena;
    private javax.swing.JRadioButton jrbArchivosPlanos;
    private javax.swing.JRadioButton jrbBD;
    private javax.swing.JRadioButton jrbXML;
    private javax.swing.JTextField jtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
